os: linux
dist: trusty
language: python
python:
- 3.5
- 3.6
- 3.7-dev
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - mingw-w64-i686-dev
    - mingw-w64-x86-64-dev

matrix:
  include:
  - os: osx
    language: generic
    python: 3.6
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.6.6/python-3.6.6-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.6/Install\ Certificates.command
    - brew install mingw-w64
  allow_failures:
  - python: "3.7-dev"

install:
- pip3 install lxml
script:
- python3 -mix -v test
- python3 -mix -v clean
- find solutions -name '*.c' | xargs -I {} python3 -mix -v generate {}
- python3 -mix -v clean
- python3 -mix -k submit -w
cache:
  pip: true
  directories:
  - $TRAVIS_BUILD_DIR/testcases
